2025-03-09 19:20:24,916 INFO    MainThread:34807 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192024-stbkte4h/logs/debug.log
2025-03-09 19:20:24,916 INFO    MainThread:34807 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192024-stbkte4h/logs/debug-internal.log
2025-03-09 19:20:24,916 INFO    MainThread:34807 [wandb_init.py:init():761] calling init triggers
2025-03-09 19:20:24,916 INFO    MainThread:34807 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-09 19:20:24,916 INFO    MainThread:34807 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 19:20:24,918 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:20:24,918 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:20:36,119 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:20:36,131 INFO    MainThread:34807 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192036-gexsss23/logs/debug.log
2025-03-09 19:20:36,132 INFO    MainThread:34807 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192036-gexsss23/logs/debug-internal.log
2025-03-09 19:20:36,132 INFO    MainThread:34807 [wandb_init.py:init():761] calling init triggers
2025-03-09 19:20:36,132 INFO    MainThread:34807 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-09 19:20:36,132 INFO    MainThread:34807 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 19:20:36,133 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:20:36,133 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:20:43,289 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:20:51,796 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:20:51,798 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:23:46,750 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:23:55,331 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:23:55,333 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:24:04,509 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:24:15,832 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:24:15,834 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:25:53,080 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:26:06,610 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:26:06,612 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:26:51,804 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:27:08,052 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:27:08,054 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:28:24,126 INFO    MainThread:34807 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 19:28:41,656 INFO    MainThread:34807 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 19:28:41,658 INFO    MainThread:34807 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 19:32:27,967 WARNING MsgRouterThr:34807 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 19:32:27,972 INFO    MsgRouterThr:34807 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
