2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_setup.py:_flush():67] Configure stats pid to 35228
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_setup.py:_flush():67] Loading settings from /Users/karanagrawal/.config/wandb/settings
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_setup.py:_flush():67] Loading settings from /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/settings
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192050-h49znrwl/logs/debug.log
2025-03-09 19:20:50,693 INFO    MainThread:35228 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/karanagrawal/Desktop/Sem 2/DL/Assignment 1/wandb/run-20250309_192050-h49znrwl/logs/debug-internal.log
2025-03-09 19:20:50,694 INFO    MainThread:35228 [wandb_init.py:init():761] calling init triggers
2025-03-09 19:20:50,694 INFO    MainThread:35228 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'DA6401_A1', 'wandb_entity': 'karan', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 64, 'loss': 'cross_entropy', 'optimizer': 'sgd', 'learning_rate': 0.1, 'momentum': 0.5, 'beta': 0.5, 'beta1': 0.5, 'beta2': 0.5, 'epsilon': 1e-06, 'weight_decay': 0.0, 'weight_init': 'random', 'num_layers': 1, 'hidden_size': 4, 'activation': 'sigmoid', '_wandb': {}}
2025-03-09 19:20:50,694 INFO    MainThread:35228 [wandb_init.py:init():784] starting backend
2025-03-09 19:20:50,694 INFO    MainThread:35228 [wandb_init.py:init():788] sending inform_init request
2025-03-09 19:20:50,729 INFO    MainThread:35228 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-09 19:20:50,730 INFO    MainThread:35228 [wandb_init.py:init():803] backend started and connected
2025-03-09 19:20:50,734 INFO    MainThread:35228 [wandb_init.py:init():896] updated telemetry
2025-03-09 19:20:50,764 INFO    MainThread:35228 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 19:20:51,137 ERROR   MainThread:35228 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
